In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
data_dir = 'data/'

In [4]:
df_train1 = pd.read_csv(os.path.join(data_dir, 'train_1.csv'))

In [5]:
df_train2 = pd.read_csv(os.path.join(data_dir, 'train_2.csv'))

In [6]:
df_train1.head()

,Page,2015-07-01,2015-07-02,2015-07-03,2015-07-04,2015-07-05,2015-07-06,2015-07-07,2015-07-08,2015-07-09,...,2016-12-22,2016-12-23,2016-12-24,2016-12-25,2016-12-26,2016-12-27,2016-12-28,2016-12-29,2016-12-30,2016-12-31
0,2NE1_zh.wikipedia.org_all-access_spider,18.0,11.0,5.0,13.0,14.0,9.0,9.0,22.0,26.0,...,32.0,63.0,15.0,26.0,14.0,20.0,22.0,19.0,18.0,20.0
1,2PM_zh.wikipedia.org_all-access_spider,11.0,14.0,15.0,18.0,11.0,13.0,22.0,11.0,10.0,...,17.0,42.0,28.0,15.0,9.0,30.0,52.0,45.0,26.0,20.0
2,3C_zh.wikipedia.org_all-access_spider,1.0,0.0,1.0,1.0,0.0,4.0,0.0,3.0,4.0,...,3.0,1.0,1.0,7.0,4.0,4.0,6.0,3.0,4.0,17.0
3,4minute_zh.wikipedia.org_all-access_spider,35.0,13.0,10.0,94.0,4.0,26.0,14.0,9.0,11.0,...,32.0,10.0,26.0,27.0,16.0,11.0,17.0,19.0,10.0,11.0
4,52_Hz_I_Love_You_zh.wikipedia.org_all-access_s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.0,9.0,25.0,13.0,3.0,11.0,27.0,13.0,36.0,10.0

In [7]:
df_train2.head()

,Page,2015-07-01,2015-07-02,2015-07-03,2015-07-04,2015-07-05,2015-07-06,2015-07-07,2015-07-08,2015-07-09,...,2017-09-01,2017-09-02,2017-09-03,2017-09-04,2017-09-05,2017-09-06,2017-09-07,2017-09-08,2017-09-09,2017-09-10
0,2NE1_zh.wikipedia.org_all-access_spider,18.0,11.0,5.0,13.0,14.0,9.0,9.0,22.0,26.0,...,19.0,33.0,33.0,18.0,16.0,27.0,29.0,23.0,54.0,38.0
1,2PM_zh.wikipedia.org_all-access_spider,11.0,14.0,15.0,18.0,11.0,13.0,22.0,11.0,10.0,...,32.0,30.0,11.0,19.0,54.0,25.0,26.0,23.0,13.0,81.0
2,3C_zh.wikipedia.org_all-access_spider,1.0,0.0,1.0,1.0,0.0,4.0,0.0,3.0,4.0,...,6.0,6.0,7.0,2.0,4.0,7.0,3.0,4.0,7.0,6.0
3,4minute_zh.wikipedia.org_all-access_spider,35.0,13.0,10.0,94.0,4.0,26.0,14.0,9.0,11.0,...,7.0,19.0,19.0,9.0,6.0,16.0,19.0,30.0,38.0,4.0
4,52_Hz_I_Love_You_zh.wikipedia.org_all-access_s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.0,16.0,19.0,9.0,20.0,23.0,28.0,14.0,8.0,7.0

In [19]:
split_pages = df_train2['Page'].apply(lambda x: x.split('_')).tolist()
merged_name_pages = []
for split_page in split_pages:
    merged_name_page = []
    merged_name_page.append('_'.join(split_page[:-3]))
    merged_name_page.extend(split_page[-3:])
    merged_name_pages.append(merged_name_page)
df_split_pages = pd.DataFrame(merged_name_pages, columns=['Name', 'Project', 'Access', 'Agent'])

In [20]:
df_split_pages.head()

               Name           Project      Access   Agent
0              2NE1  zh.wikipedia.org  all-access  spider
1               2PM  zh.wikipedia.org  all-access  spider
2                3C  zh.wikipedia.org  all-access  spider
3           4minute  zh.wikipedia.org  all-access  spider
4  52_Hz_I_Love_You  zh.wikipedia.org  all-access  spider

In [24]:
columns = df_train2.columns.values
df_train_final = pd.concat([df_train2[columns[0]], df_split_pages, df_train2[columns[1:]]], axis=1)

In [25]:
df_train_final.head()

,Page,Name,Project,Access,Agent,2015-07-01,2015-07-02,2015-07-03,2015-07-04,2015-07-05,...,2017-09-01,2017-09-02,2017-09-03,2017-09-04,2017-09-05,2017-09-06,2017-09-07,2017-09-08,2017-09-09,2017-09-10
0,2NE1_zh.wikipedia.org_all-access_spider,2NE1,zh.wikipedia.org,all-access,spider,18.0,11.0,5.0,13.0,14.0,...,19.0,33.0,33.0,18.0,16.0,27.0,29.0,23.0,54.0,38.0
1,2PM_zh.wikipedia.org_all-access_spider,2PM,zh.wikipedia.org,all-access,spider,11.0,14.0,15.0,18.0,11.0,...,32.0,30.0,11.0,19.0,54.0,25.0,26.0,23.0,13.0,81.0
2,3C_zh.wikipedia.org_all-access_spider,3C,zh.wikipedia.org,all-access,spider,1.0,0.0,1.0,1.0,0.0,...,6.0,6.0,7.0,2.0,4.0,7.0,3.0,4.0,7.0,6.0
3,4minute_zh.wikipedia.org_all-access_spider,4minute,zh.wikipedia.org,all-access,spider,35.0,13.0,10.0,94.0,4.0,...,7.0,19.0,19.0,9.0,6.0,16.0,19.0,30.0,38.0,4.0
4,52_Hz_I_Love_You_zh.wikipedia.org_all-access_s...,52_Hz_I_Love_You,zh.wikipedia.org,all-access,spider,NaN,NaN,NaN,NaN,NaN,...,16.0,16.0,19.0,9.0,20.0,23.0,28.0,14.0,8.0,7.0

In [30]:
df_train_sample = df_train_final.dropna().sample(n=100, random_state=42).reset_index(drop=True)

In [31]:
df_train_sample.head()

,Page,Name,Project,Access,Agent,2015-07-01,2015-07-02,2015-07-03,2015-07-04,2015-07-05,...,2017-09-01,2017-09-02,2017-09-03,2017-09-04,2017-09-05,2017-09-06,2017-09-07,2017-09-08,2017-09-09,2017-09-10
0,Ostermontag_de.wikipedia.org_all-access_all-ag...,Ostermontag,de.wikipedia.org,all-access,all-agents,32.0,29.0,29.0,31.0,25.0,...,19.0,18.0,19.0,32.0,33.0,40.0,36.0,24.0,25.0,26.0
1,Alois_Brunner_de.wikipedia.org_all-access_all-...,Alois_Brunner,de.wikipedia.org,all-access,all-agents,95.0,138.0,110.0,89.0,120.0,...,137.0,116.0,119.0,265.0,250.0,380.0,254.0,180.0,124.0,190.0
2,松来未祐_ja.wikipedia.org_all-access_all-agents,松来未祐,ja.wikipedia.org,all-access,all-agents,1381.0,851.0,600.0,1358.0,2083.0,...,1064.0,1100.0,1169.0,932.0,955.0,992.0,1097.0,943.0,1023.0,1150.0
3,ラマダーン_ja.wikipedia.org_desktop_all-agents,ラマダーン,ja.wikipedia.org,desktop,all-agents,809.0,774.0,745.0,395.0,439.0,...,175.0,93.0,105.0,141.0,150.0,115.0,149.0,113.0,63.0,73.0
4,Fabian_Hambüchen_de.wikipedia.org_mobile-web_a...,Fabian_Hambüchen,de.wikipedia.org,mobile-web,all-agents,24.0,49.0,31.0,41.0,43.0,...,67.0,137.0,80.0,53.0,58.0,38.0,55.0,98.0,99.0,80.0

In [32]:
len(df_train_sample)

100

In [33]:
df_train_sample.to_csv(os.path.join(data_dir, 'train_clean_sample.csv'), index=False)

In [ ]:
%%time
df_train_final.to_csv(os.path.join(data_dir, 'train_final.csv'), index=False)